version: "3.9"

volumes:
    postgress_data:
    loki:
    loki_config:
    prometheus_config:
    prometheus_data:
    grafana_config:
    grafana_data:

networks:
    overmoney:
    
services:
    db:
        image: postgres
        container_name: overmoney_db
        volumes:
            - postgress_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
            POSTGRES_DB: dev
        networks:
            - overmoney
        ports:
            - 5432:5432
    api:
        build: 
            context: .
            dockerfile: ./Overmoney.Api/Dockerfile
        container_name: overmoney_api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__Database=Host=overmoney_db:5432;Database=dev;Username=dev;Password=dev
            - ASPNETCORE_HTTP_PORTS=80
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Password=password
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - AutoMigrate=true
        networks:
            - overmoney
        ports:
            - 8085:80
            - 8081:8081
        volumes:
            - ~/.aspnet/https:/https:ro
    portal:
        build:
            context: ./Overmoney.Portal/
            dockerfile: ./Dockerfile
        container_name: overmoney_portal
        environment:
            - VITE_API_URL="https://overmoney_api:80/"
        networks:
            - overmoney
        ports:
            - 80:80

# OBSERVABILITY
    loki:
        restart: always
        image: grafana/loki
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
          - loki:/loki
          - loki_config:/etc/loki
        networks:
          - overmoney

    prometheus:
        restart: always
        image: prom/prometheus
        ports:
          - 9090:9090
        volumes:
          - ./configs/prometheus:/etc/prometheus/
          - prometheus_data:/prometheus
        networks:
          - overmoney

    grafana:
        restart: always
        environment:
          - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
        entrypoint:
          - sh
          - -euc
          - |
            mkdir -p /etc/grafana/provisioning/datasources
            cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              access: proxy 
              orgId: 1
              url: http://loki:3100
              basicAuth: false
              isDefault: true
              version: 1
              editable: false
            - name: Prometheus
              type: prometheus
              access: proxy
              orgId: 1
              url: http://prometheus:9090
              basicAuth: false
              isDefault: false
              version: 1
              editable: false
            EOF
            /run.sh
        image: grafana/grafana:latest
        ports:
          - 3000:3000
        volumes:
          - grafana_config:/var/lib/grafana
          - grafana_data:/etc/grafana
          - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
          - ./configs/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
        networks:
          - overmoney